### ISSUE TITLE
error at line  ret_vars = tf.while_loop(cond=beam_cond, body=beam_step, loop_vars=loop_vars, back_prop=False) of function setup_beam

### ISSUE THREAD

**Issue by qinghua2016** [avati/nlc#10]
When I build the model ,it have the error at line  ret_vars = tf.while_loop(cond=beam_cond, body=beam_step, loop_vars=loop_vars, back_prop=False) of function setup_beam. The error is as follows:
ValueError: The shape for NLC/while/Merge_1:0 is not an invariant for the loop. It enters the loop with shape (1,), but has shape (?,) after one iteration. Provide shape invariants using either the `shape_invariants` argument of tf.while_loop or set_shape() on the loop variables.
Can you fix it ?@avati

**Comment by allenanie** [comment]
This fix hasn't been merged to master branch yet, so anyone pulling from master branch will still have a broken `setup_beam()`, please merge the issue :) @avati @zxie

**Comment by avati** [comment]
Merged

**Comment by allenanie** [comment]
Hmmmm I still get the error:
```
ValueError: Shapes must be equal rank, but are 2 and 1
	From merging shape 3 with other shapes. for 'NLC/while/Logistic/packed' (op: 'Pack') with input shapes: [?,52], [100,52], [100,52], [0,52], [52].
```
And based on my IDE, the argument in 
```
ret_vars = tf.while_loop(cond=beam_cond, body=beam_step, loop_vars=loop_vars, shape_invariants=loop_var_shapes, back_prop=False)
```
`shape_invariants` is not an expected argument to pass in in `tf.while_loop()`...

**Comment by zxie** [comment]
Hmmm what version of tensorflow are you using?

**Comment by allenanie** [comment]
OK. It seems that by updating tensorflow on my laptop, I'm able to see that argument. However, I ran the code on the server with tensorflow (0.12.0rc0) and encountered the error.

**Comment by windweller** [comment]
On my laptop (where IDE runs) it's tensorflow (0.10.0rc0)
