### ISSUE TITLE
Is the original Theano code available as well?

### ISSUE THREAD

**Issue by andrewilyas** [avati/nlc#12]
I know this is a port from existing code written in Theano; is the original code also available somewhere? I haven't been able to find it.

**Comment by zxie** [comment]
It's no longer under development, but you can find it here: https://bitbucket.org/zxie/nlc_models/src

**Comment by ghost** [comment]
@zxie @avati  
"cfg.py" file we have to provide TRAIN_FILES and VALID_FILES. I have CoNLL 2014 shared task dataset. In what format I should convert this dataset to configure with your code. 

Is it in format of  "list of source sentence" and "list target sentence"?
