### ISSUE TITLE
Minor detail on decoder's init_state

### ISSUE THREAD

**Issue by allenanie** [avati/nlc#14]
So I thought decoder would initialize its initial states by taking in the last time steps of the encoder...

In the code, however, this is not happening, since the decoder initializes its initial states with 0s during training...effectively the only Tensorflow link between encoder and decoder is through the attention map. Is this an implementation decision? Or is this standard and more general?

**Comment by avati** [comment]
It's intentional. The "last state" is also a bit ambiguous since we have two of them (bidirectional) but the decoder is uni directional. Also, the attn paper has this architecture (I.e no other connections other than attn)

**Comment by allenanie** [comment]
Hmmmmmmm is it a standard practice? THANK YOU for answering so quickly!

**Comment by avati** [comment]
I believe so, when you are using attention the decoder starts with 0 hidden state.
