### ISSUE TITLE
Unaviable data

### ISSUE THREAD

**Issue by king-menin** [avati/nlc#17]
the link http://neuron.stanford.edu/nlc/data/nlc-train.tar is unaviable :(

**Comment by axansh** [comment]
http://neuron.stanford.edu/nlc/data/nlc-train.tar is not available.
Can you point us to alternative data set?

**Comment by mzeidhassan** [comment]
@zxie Can you please provide the correct URL to download the data?

**Comment by zxie** [comment]
Please see https://github.com/stanfordmlgroup/nlc/issues/3

We can't distribute the data ourselves

**Comment by mojesty** [comment]
@axansh the alternative is to either request NUCLE corpus or Lang-8 corpus. I succeeded in obtaining them from their official web sites, but note that they are for educational and non-commercial use only.
