### ISSUE TITLE
Can't get the data

### ISSUE THREAD

**Issue by xubenben** [avati/nlc#3]
Hello,

I run the code and get this : IOError: [Errno socket error] [Errno 113] No route to host. 

Could you put the data on google drive or something else, thanks~~

@zxie

**Comment by zxie** [comment]
The datasets can be requested from the following webpages (have licenses):
- http://cl.naist.jp/nldata/lang-8/
- http://www.comp.nus.edu.sg/~nlp/conll14st.html
- http://www.comp.nus.edu.sg/~nlp/conll13st.html

**Comment by hadifar** [comment]
The download link also available from here:
https://sites.google.com/site/naistlang8corpora/
