### ISSUE TITLE
Meet "disturbing performance" when decode sentence

### ISSUE THREAD

**Issue by xubenben** [avati/nlc#4]
Hello,

I have get the lang-8 data and run your code with 40 epoch, and when I decode sentence, I meet "disturbing performance".

when the input sentence is very short, it woks well:
![image](https://cloud.githubusercontent.com/assets/3480189/15281861/9821766a-1b71-11e6-8d01-161800325d3a.png)

However, when input long sentence from CoNLL2014 test data, it works "distrubing":
![image](https://cloud.githubusercontent.com/assets/3480189/15281882/c81cf736-1b71-11e6-8bcf-dbff0347d404.png)

And I notice you haven't integrate LM into your model.

Best,
Jun

**Comment by avati** [comment]
Hi Jun,
Thanks for testing the code. This is still under development as the porting is not yet complete.

**Comment by lelour** [comment]
I can't get the two tar files. Connection refused. How can i get them?

**Comment by huangshenno1** [comment]
@zxie @avati @xubenben I requested the lang-8 corpora by emailing komachi@is.naist.jp but was rejected by the email server. It seems that this email address is no longer available. Could anyone provide a new lang-8 corpora?

**Comment by carlWM** [comment]
@xubenben I could not get any responses from  komachi@is.naist.jp , too, could you provide me with lang-8 or CoNLL datasets? Thank you.

**Comment by huangshenno1** [comment]
@carlWM 
```
_NLC_TRAIN_URL = "http://neuron.stanford.edu/nlc/data/nlc-train.tar"
_NLC_DEV_URL = "http://neuron.stanford.edu/nlc/data/nlc-valid.tar"
```
Now the url is available and the dataset seems to be Lang-8. Besides, CoNLL dataset can be obtained from its official website.

**Comment by carlWM** [comment]
@huangshenno1
 Thank you!

**Comment by zxie** [comment]
Closing this for now; please open new issue if encounter other problems.

**Comment by y521263** [comment]
"http://neuron.stanford.edu/nlc/data/nlc-train.tar"
the url is unavailable , could you provide me with lang-8 or CoNLL datasets? Thank you.

**Comment by babaozhouy5** [comment]
@y521263 You can send an email to "komachi@tmu.ac.jp", and ask for the lang-8 datasets.

**Comment by mayank-kishore** [comment]
@y521263 , @babaozhouy5 what is the updated url for the dataset
>"http://neuron.stanford.edu/nlc/data/nlc-train.tar

**Comment by ghost** [comment]
@xubenben @avati  @zxie 
since the  URL link is not working.
_NLC_TRAIN_URL = "http://neuron.stanford.edu/nlc/data/nlc-train.tar"
_NLC_DEV_URL = "http://neuron.stanford.edu/nlc/data/nlc-valid.tar"

Can you please guide me in what format it returns data. I have CoNLL -2014 shared task dataset. Kindly guide us so that I can make relevant changes. Please reply at the earliest.
