### ISSUE TITLE
tar files can not download

### ISSUE THREAD

**Issue by lelour** [avati/nlc#5]
I can't get the two tar files. Connection refused. How can i get them?

**Comment by tokestermw** [comment]
You can ask the kind folks over here. http://cl.naist.jp/nldata/lang-8/

**Comment by LiuZichuan** [comment]
Since the tar is not available. May I ask the data format in the .x.txt and .y.txt file?

**Comment by avati** [comment]
the x.txt and y.txt have the wrong and right sentences, one per line. The line numbers of the two files correspond to a pair of wrong/right sentences.
