### ISSUE TITLE
how to use lang-8 and CoNLL data?

### ISSUE THREAD

**Issue by XiaoranJin** [avati/nlc#6]
Hi, I've got lang-8 and CoNLL dataset. Any clue about how to input the data into your training scripts?

Would really appreciate if you can show what the data structure is in "nlc-train.tar" and "nlc-valid.tar". 

Thanks!

**Comment by avati** [comment]
Something like this:

```
$ tar tvf nlc-valid.tar 
-rw-r--r-- avati/avati  312524 2016-04-11 14:17 valid.x.txt
-rw-r--r-- avati/avati  323750 2016-04-11 14:17 valid.y.txt

$ tar tvf nlc-train.tar 
-rw-r--r-- avati/users 50842953 2016-05-19 10:44 train.x.txt
-rw-r--r-- avati/users 51878318 2016-05-19 10:45 train.y.txt
```

You can also look at nlc_data.py to see what the code checks for.

**Comment by kbpranay** [comment]
hey guys anyone got a link for lang 8 data for training? If yes please send me a download link. @XiaoranJin @avati

**Comment by ghost** [comment]
@XiaoranJin  
Did you understand what the data structure is in "nlc-train.tar" and "nlc-valid.tar" ?

**Comment by morusu** [comment]
@rajism did you have the "nlc-train.tar" and "nlc-valid.tar" ? can u share me?

**Comment by morusu** [comment]
@avati did you have the "nlc-train.tar" and "nlc-valid.tar" ? can u share me?
